
TEENCODE_MAP = {
    "khong": "không",
    "văng": "mất kết nối",
    "ak": "ạ",
    "bin": "pin",
    "ad": "admin",
    "ko": "không",
    "k": "không",
    "khum": "không",
    "hok": "không",
    "hong": "không",
    "dc": "được",
    "đc": "được",
    "sp": "sản phẩm",
    "cx": "cũng",
    "vs": "với",
    "đt": "điện thoại",
    "dt": "điện thoại",
    "bh": "bảo hành",
    "nv": "nhân viên",
    "ok": "tốt", 
    "oke": "tốt",
    "okay": "tốt",
    "sd": "sử dụng",
    "mng": "mọi người",
    "mn": "mọi người",
    "thik": "thích",
    "nhìu": "nhiều",
    "bit": "biết",
    "lắc": "giật",
    "tgdd": "thế giới di động",
    "j": "gì", "z": "vậy", "vs": "với", "wifi": "wifi",
    "lun": "luôn", "luon": "luôn", "xog": "xong", "xong": "xong",
    "r": "rồi", "roi": "rồi", "hs": "học sinh", "nt": "nhắn tin",
    "tl": "trả lời", "cmt": "bình luận", "fb": "facebook", "ytb": "youtube",
    "ig": "instagram", "đx": "được", "dk": "được", "lag": "giật",
    "tuột pin": "hết pin nhanh", "tụt pin": "hết pin nhanh",
    "hao pin": "hết pin nhanh", "pin trâu": "pin bền", "pin khỏe": "pin bền",
    "ngon": "tốt", "ok": "tốt", "oke": "tốt", "okay": "tốt",
    "tạm được": "trung bình", "tạm ổn": "trung bình", "bth": "bình thường",
    "bt": "bình thường", "chả": "không", "đéo": "không",
    "vl": "quá", "vcl": "quá", "cực kì": "cực kỳ", "đơ": "đơ", "đứng máy": "đơ",
    "m": "mình", "e": "em", "a": "anh", "c": "chị", "mk": "mình", "t": "tôi",
    "ntn": "như thế nào", "bn": "bao nhiêu", "ntn": "như thế nào",
    "vs": "với", "đx": "được", "dc": "được",
}
